apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - files:
      - netapp-harvest.yaml=netapp-harvest.yaml
    name: alert-templates-netapp

patches:
  - path: volume.yaml
