apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - files:
      - netapp.yaml.tmpl=netapp.yaml.tmpl
    name: alert-templates-netapp
    options:
      disableNameSuffixHash: true

patches:
  - path: volume.yaml
