apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  template:
    spec:
      initContainers:
        - name: rule-watcher
          volumeMounts:
            - name: rule-templates-prometheus-ksm
              mountPath: /var/prometheus/rule-templates/prometheus-ksm
      volumes:
        - name: rule-templates-prometheus-ksm
          configMap:
            name: alert-templates-prometheus-ksm
