apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-rule
spec:
  template:
    spec:
      # Patches $ENVIRONMENT and $PROVIDER inside alerts templates and places
      # them into an emptyDir: {} for thanos-rule to read
      initContainers:
        - name: render-alerts
          image: alpine
          args:
            - /bin/sh
            - -c
            - |
              apk add --no-cache gettext;
              for file in $(find /var/thanos/rule-templates/ -type f); do
                # If the file has a .tmpl or .tpl extension - remove it
                [ "$f" = "${f%.tmpl}" -o "$f" = "${f%.tpl}" ] && f="${f%.tmpl}" && f="${f%.tpl}"
                echo $f
                envsubst '${ENVIRONMENT},${PROVIDER}' < $file > /var/thanos/rules/$(basename $f);
              done;
          volumeMounts:
            - name: rules-rendered
              mountPath: /var/thanos/rules
      containers:
        - name: thanos-rule
          volumeMounts:
            - name: rules-rendered
              mountPath: /var/thanos/rules
      volumes:
        # $patch: replace doesn't seem to work here, so dropping the upstream
        # rules volume completely and using a new one for rendered alerts.
        - $patch: delete
          name: rules
        - name: rules-rendered
          emptyDir: {}
