apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-rule
spec:
  template:
    spec:
      initContainers:
        - name: render-alerts
          volumeMounts:
            - name: rule-templates-exp
              mountPath: /var/thanos/rule-templates/exp
      volumes:
        - name: rule-templates-exp
          configMap:
            name: alert-templates-exp
