apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  template:
    spec:
      initContainers:
        - name: rule-watcher
          volumeMounts:
            - name: rule-templates-capacity-experiments
              mountPath: /var/prometheus/rule-templates/capacity-experiments
      volumes:
        - name: rule-templates-capacity-experiments
          configMap:
            name: alert-templates-capacity-experiments
