apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - files:
      - cis-aws.yaml.tmpl=cis-aws.yaml.tmpl
    name: alert-templates-cis-aws
    options:
      disableNameSuffixHash: true

patches:
  - path: volume.yaml
