apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  template:
    spec:
      initContainers:
        - name: rule-watcher
          volumeMounts:
            - name: rule-templates-cis-aws
              mountPath: /var/prometheus/rule-templates/cis-aws
      volumes:
        - name: rule-templates-cis-aws
          configMap:
            name: alert-templates-cis-aws
