apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - files:
      - kube-applier.yaml.tmpl=kube-applier.yaml.tmpl
    name: alert-templates-kube-applier
    options:
      disableNameSuffixHash: true

patches:
  - path: volume.yaml
