apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - files:
      - wiresteward.yaml.tmpl
    name: alert-templates-wiresteward
    options:
      disableNameSuffixHash: true

patches:
  - path: volume.yaml
