apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - files:
      - merit.yaml.tmpl=merit.yaml.tmpl
    name: alert-templates-merit
    options:
      disableNameSuffixHash: true

patches:
  - path: volume.yaml
