apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  template:
    spec:
      initContainers:
        - name: rule-watcher
          volumeMounts:
            - name: rule-templates-merit
              mountPath: /var/prometheus/rule-templates/merit
      volumes:
        - name: rule-templates-merit
          configMap:
            name: alert-templates-merit
