apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-rule
spec:
  template:
    spec:
      initContainers:
        - name: render-alerts
          volumeMounts:
            - name: rule-templates-common
              mountPath: /var/thanos/rule-templates/common
      volumes:
        - name: rule-templates-common
          configMap:
            name: alert-templates-common
