#!/bin/bash

# Redirect output to stderr.
exec 1>&2

exit_code=0

# List of changed files, excluding deleted ones

if [[ -z "${GIT_CMD}" ]]; then
  GIT_CMD="git diff --name-only --cached --diff-filter=d"
else
  GIT_CMD=${GIT_CMD}
fi

PROM_VERSION="v2.47.0"

function is_yaml_extension() {
  local file=$1
  if [[ "${file}" == *yaml || "${file}" == *yml || "${file}" == *yaml.tmpl || "${file}" == *yml.tmpl ]]; then
    return 0
  fi

  return 1
}

function is_valid_yaml() {
  local file=$1
  if is_yaml_extension "${file}"; then
    if yq -v "${file}" ; then
      return 0
    fi
    exit_code=1
  fi

  return 1
}

# Check alerts
function check_alerts() {
  local files=$(${GIT_CMD})
  for f in ${files}
  do
    if is_valid_yaml "${f}"; then
      if [[ $(head -1 "${f}") =~ "PROMETHEUS RULES" ]]; then
        docker run -i --entrypoint promtool -v $PWD/${f}:$PWD/${f} docker.io/prom/prometheus:${PROM_VERSION} check rules $PWD/${f} &> /dev/null
        if [ $? -ne 0 ]; then
            echo "err: Found misconfigured alerts staged in ${f}"
            docker run -i --entrypoint promtool -v $PWD/${f}:$PWD/${f} docker.io/prom/prometheus:${PROM_VERSION} check rules $PWD/${f}
            exit_code=1
        fi
      fi
    fi
  done
}

# checks
check_alerts

exit ${exit_code}
