name: run-pre-commit-checks

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install packages
        run: |
          sudo apt-get -y install git
      - name: Run pre-commit checks script
        run: make hooks-pre-commit-run
